'use strict';

// Readable default-level maps.
// Legend:
//   # wall brick, G normal green brick, . empty route
//   B split, Y heavy, V shotgun, R bomb, P laser
// Each row is 25 cells wide. The first 22 rows form the editable brick field.

var DEFAULT_LEVELS = [
  {
    id: 1,
    name: '入门练习',
    rows: [
      '#########################',
      '#GGGGGGGGGGGGGGGGGGGGGGG#',
      '#G....GGGGG...GGG......G#',
      '#G...BGGGGG...GGG......G#',
      '#G....GGGGG...GGG.Y....G#',
      '#G.....................G#',
      '#GGGG######...GGGGGGGGGG#',
      '#GGGGGGGGGG....GGGGGGGGG#',
      '#GG......V....G.GGGGGGGG#',
      '#GG......GG...#######GGG#',
      '#GG......GG...G.RGGGGGGG#',
      '#GG....................G#',
      '#G....G.GGG...GG.......G#',
      '#G.######GG.P.GG.......G#',
      '#G....GGG.G...GG######GG#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#'
    ]
  },
  {
    id: 2,
    name: '回廊迷宫',
    rows: [
      '#########################',
      '#GGGGGGGGGGGGGGGGGGG..#G#',
      '#GGGGGGGGGGGGGGGGGGG..#G#',
      '#GGG..................#G#',
      '#GGG..................#G#',
      '#GGG.###############..#G#',
      '#GGG..#PGGGGGGGGGGGGGG#G#',
      '#GGG..#G.....GGGGGGGGGGG#',
      '#GGG..#G.....GB.GGGGGGGG#',
      '#GGG..#G.....GGGGGGGGGGG#',
      '#GGG..#GGGGG.GGGGGGGGGGG#',
      '#GYG..#GGG.GG......GGGGG#',
      '#GGG..#GGGGGG......GGGGG#',
      '#GGG..#GGGGGG......GGVGG#',
      '#GGG..#GGGR.GGGGGGGGGGGG#',
      '#GGG..#G....GGG.GGGGGGGG#',
      '#GGG..###############GGG#',
      '#GGG..................GG#',
      '#GGG..................#G#',
      '####################..#G#',
      '#GGGGGGGGGGGGG.....G..#G#',
      '#GGGGGGGGGGGGG.....G..#G#'
    ]
  },
  {
    id: 3,
    name: '鱼形迷宫',
    rows: [
      '#########################',
      '#....GGGGGGGGGGGGGGGGGGG#',
      '#..#.#G....GGGGG.....GGG#',
      '#..#.#B....G###G.....GGG#',
      '#..#.#G...##...##.V..GGG#',
      '#..#.#G..#.......#...GGG#',
      '#..#.#GG#.........#GGGGG#',
      '#..#.###...........##GGG#',
      '#..###...............#GG#',
      '#..#..................#G#',
      '#............R.........##',
      '#..#...................G#',
      '#..#.#...............#GG#',
      '#..#GG##...........##GGG#',
      '#..#...G#.........#GGGGG#',
      '#..#...GG#......##GGGGGG#',
      '#..#...YGG#....#GG.....G#',
      '#..#...GG#.....#GG.....G#',
      '#..#...G#.......#G..P..G#',
      '#..#GGG#.........#.....G#',
      '#..#GGGG##.....##GGGGGGG#',
      '###########....##########'
    ]
  },
  {
    id: 4,
    name: '折线回弹',
    rows: [
      '#########################',
      '#GGGGGGGGGGGGGGGGGGGGGGG#',
      '#GG.....G.G...G.G.....GG#',
      '#.G.....GGG...GGG.....GG#',
      '#GG...................G.#',
      '#GG...................GG#',
      '#G.GVGGG.GG....GGGG.GGGG#',
      '#G#########...BGGG.GGGG.#',
      '#GGG.GGGGG....#########G#',
      '#G.GGGGG.GG....GGGGG.GGG#',
      '#GGGGG.GGGG...GGGG.GGGRG#',
      '#GGG.................G.G#',
      '#GG..................GGG#',
      '#.GGGGG.GGG...GGGG.GGGGG#',
      '#GGGG######...######GG..#',
      '#GG.GGGGG.G...G.GGGGG.GG#',
      '#.GGGGG.GPG...GGGGGYGGGG#',
      '#GGGG.GGGGG.GGGGG.GGGGG.#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#'
    ]
  },
  {
    id: 5,
    name: '双岛通道',
    rows: [
      '#########################',
      '#GGGGGGGGGGGGGGGGGGGGGGG#',
      '#G.......GGGGG.GG.....GG#',
      '#GG...P.GGGG.GGGB.....GG#',
      '#GG...G###########G....G#',
      '#G....GG.GG....GGGG...GG#',
      '#GG....GGGG...GGGG....GG#',
      '#GG...GGGG.#...G.GG....G#',
      '#GG...GGGGG#...GGGG...GG#',
      '#.V...................GG#',
      '#GG...................RG#',
      '#GG...GGG.G###...GG...GG#',
      '#.G...G.GGG###...GG...GG#',
      '#GG...GGGGG###G...G...G.#',
      '#GG...G########...G...GG#',
      '#G....GGGYGGG.GG......GG#',
      '#GG....GGGGG.GGG......G.#',
      '#GG...GGGG.GGGGG.GG...GG#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#'
    ]
  },
  {
    id: 6,
    name: '十字回廊',
    rows: [
      '#########################',
      '#GGGGGGGGGGGGGGGGGGGGGGG#',
      '#GGGGG.GGGGG.GGGGG.GGGGG#',
      '#GGGGVGGGG.GGGGG.GGGGG.G#',
      '#G.....................G#',
      '#......................G#',
      '#GGGG...GGG###BGG..GGGGG#',
      '#GG.GG..G.G###G.G..GG.GG#',
      '#.R###..######GGG...GGGG#',
      '#GGGG...GG.....GG..GGGG.#',
      '#GGGGG..G.......G..GG.PG#',
      '#G.GGG..GGG######..###GG#',
      '#GGGGG..GGG###GGG..GGGG.#',
      '#G.....................G#',
      '#G.....................G#',
      '#GGGGG.GGGGG.GGGGG.YGGGG#',
      '#GGG.GGGGG.GGGGG.GGGGG.G#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#'
    ]
  },
  {
    id: 7,
    name: '阶梯墙阵',
    rows: [
      '#########################',
      '#GGGGGGGGGGGGGGGGGGGGGGG#',
      '#GGGG.GGGGG.GGGGGGGGGGGG#',
      '#G.....................G#',
      '#......................G#',
      '#G..B.#GGGG.GGR#G.GGG...#',
      '#G..G###############G..G#',
      '#G....GGGGGGG#GGGGG#G..G#',
      '#G..G#.G.........GG#G...#',
      '#G...#GG.........GG##..G#',
      '#G..G#GG.........GG#...G#',
      '#G..G#.G.........G##G..G#',
      '#G...#GG.........#G.G..G#',
      '#G..G#G#.GGGGG.G#GG#Y..G#',
      '#G..G###############G..G#',
      '#G..G#GGVGGGGG#GGGGPG..G#',
      '#G.....................G#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#'
    ]
  },
  {
    id: 8,
    name: '窄门反射',
    rows: [
      '#########################',
      '#GGGGGGGGGGGGGGGGGGGGGGG#',
      '#GGGGGGGGGG...G.GGGGG.GG#',
      '#GGGGGGGGGG...GGGGG.GGGG#',
      '#GG...................GG#',
      '#GG...................GG#',
      '#G.B#GGG.GG...PGGGGGGGGG#',
      '#G#########...GGGG.GG#GG#',
      '#GGG.GGGGG....#########G#',
      '#GGGGGGGGG#....GGGG#.GGG#',
      '#GGGGGGGG#G...GGGG#GGRGG#',
      '#GGG.................GGG#',
      '#GG..................GGG#',
      '#.GGGG#.GGG...G#GGGGGGGG#',
      '#GGGG######...######GGG.#',
      '#GG.#GGGY.G...G.GGVGG.GG#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#'
    ]
  },
  {
    id: 9,
    name: '环形压力',
    rows: [
      '#########################',
      '#GGGGGGGGGGGGGGGGGGGGGGG#',
      '#G.GGGGG.GGGGG.GGGGGGGGG#',
      '#GG....GG#GG.GGYGG....GG#',
      '#GG...G###########G....G#',
      '#GG...GGGGG....GG#G...GG#',
      '#GG...GGGGG...GGGGG...GG#',
      '#GV...GG#GG#...GGGG...GG#',
      '#GG...GGGG##...GGGG...GG#',
      '#.G...................PG#',
      '#GG...................GG#',
      '#GG...G#G.B###...GG...GG#',
      '#GG...#GGGG###...GG...GG#',
      '#GG...GGGGG####...G...G.#',
      '#GG...G########...R...GG#',
      '#G....#GGGGG#GGG......GG#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#'
    ]
  },
  {
    id: 10,
    name: '终局迷宫',
    rows: [
      '#########################',
      '#GGGGGGGGGGGGGGGGGGGGGGG#',
      '#GGGGGGGGGGGGGGGGGGGGGGG#',
      '#GG#GGPGGGGGGGVGGGGG#GGG#',
      '#G.....................G#',
      '#......................G#',
      '#GGGG...GGG###G#G..G#GGG#',
      '#GBGGG..G.####G.G..#G.GG#',
      '#GG###..######GGG...GGYG#',
      '#GGGGG..#G.....GG..GGGG.#',
      '#GGGGG..GG.....G#..GGGGG#',
      '#G.GGG..GGG######..###GG#',
      '#GGGG#..GRG####GG..GGGGG#',
      '#G.....................G#',
      '#G.....................G#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#'
    ]
  }
];

module.exports = {
  defaultLevels: DEFAULT_LEVELS
};
