'use strict';

// Readable default-level maps.
// Legend:
//   # wall brick, G normal green brick, . empty route
//   B split, Y heavy, V shotgun, R bomb, P laser
// Each row is 25 cells wide. The first 22 rows form the editable brick field.

var DEFAULT_LEVELS = [
  {
    id: 1,
    name: '分裂教学',
    rows: [
      '#########################',
      '#..BBBBBBBBBBBBBBBBBBB..#',
      '#..B.GGG.B.....B.GGG.B..#',
      '#..GGGGGGG.....GGGGGGG..#',
      '#.......................#',
      '#..GGGGGGGGGGGGGGGGGGG..#',
      '#..G..B...........B..G..#',
      '#..G.BBB..GGGGG..BBB.G..#',
      '#..GBBBBB.GGGGG.BBBBBG..#',
      '#..G......GGGGG......G..#',
      '#..G......GGGGG......G..#',
      '#..GBBBBBBBBBBBBBBBBBG..#',
      '#..GGGGGGGGGGGGGGGGGGG..#',
      '#..GGGGGGGGGGGGGGGGGGG..#',
      '#...........G...........#',
      '#...........G...........#',
      '#...........G...........#',
      '#..BBB......G......BBB..#',
      '#..BBB....GGGGG....BBB..#',
      '#.........GGGGG.........#',
      '#.........GGGGG.........#',
      '#..GGGGGGGGGGGGGGGGGGG..#'
    ]
  },
  {
    id: 2,
    name: '重弹教学',
    rows: [
      '#########################',
      '#..YYYYYYYYYYYYYYYYYYY..#',
      '#..Y.................Y..#',
      '#..GGGGGGGG...GGGGGGGG..#',
      '#.......................#',
      '#.......................#',
      '#....YYYYY.###.YYYYY....#',
      '#..........###..........#',
      '#....YYYYY.###.YYYYY....#',
      '#.......................#',
      '#..GGGGGGGG...GGGGGGGG..#',
      '#.....YYYYYYYYYYYYY.....#',
      '#.......................#',
      '#..Y....Y.......Y....Y..#',
      '#.......................#',
      '#..GGGGGGGG...GGGGGGGG..#',
      '#..########...########..#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#..GGGGGGGG...GGGGGGGG..#',
      '#..########...########..#'
    ]
  },
  {
    id: 3,
    name: '霰弹教学',
    rows: [
      '#########################',
      '#..VVVVV.........VVVVV..#',
      '#..VVVVV.........VVVVV..#',
      '#..GGG...GGGGGGG...GGG..#',
      '#..GGG...GGGGGGG...GGG..#',
      '#..GGG.............GGG..#',
      '#..GGGVVVVVVVVVVVVVGGG..#',
      '#..GGG.............GGG..#',
      '#..VVVVV.........VVVVV..#',
      '#..GGGGGGGGGGGGGGGGGGG..#',
      '#..GGGGGGGGGGGGGGGGGGG..#',
      '#....VVVVVGGGGGVVVVV....#',
      '#.......................#',
      '#..VVVVVV.......VVVVVV..#',
      '#.......................#',
      '#..G.................G..#',
      '#..GGGGGGGGGGGGGGGGGGG..#',
      '#..GGGGGGGGGGGGGGGGGGG..#',
      '#..G.................G..#',
      '#..G.................G..#',
      '#..G..VVVVVVVVVVVVV..G..#',
      '#..GGGGGGGGGGGGGGGGGGG..#'
    ]
  },
  {
    id: 4,
    name: '炸弹教学',
    rows: [
      '#########################',
      '#.......................#',
      '#..RRRRR....RRR....RRR..#',
      '#..R.R.R....R.R....R.R..#',
      '#..RRRRR....RRR....RRR..#',
      '#.......................#',
      '#.....RRR..RRRRR..RRR...#',
      '#.....R.R..R.R.R..R.R...#',
      '#.....RRR..RRRRR..RRR...#',
      '#..GGGGGGGGGGGGGGGGGGG..#',
      '#..GGGGGGGGGGGGGGGGGGG..#',
      '#....RRRRRR...RRRRRR....#',
      '#.......................#',
      '#..RRRRRR.......RRRRRR..#',
      '#.......................#',
      '#..GGGGGGGGGGGGGGGGGGG..#',
      '#..GGGGGGGGGGGGGGGGGGG..#',
      '#.......................#',
      '#....RRRRRRRRRRRRRRR....#',
      '#....RGGGGGGGGGGGGGR....#',
      '#....RGGGGGGGGGGGGGR....#',
      '#....RRRRRRRRRRRRRRR....#'
    ]
  },
  {
    id: 5,
    name: '激光教学',
    rows: [
      '#########################',
      '#..P.GG.P..GGG..P.GG.P..#',
      '#..P.GG.P..GGG..P.GG.P..#',
      '#..P.GG.P..GGG..P.GG.P..#',
      '#.......................#',
      '#.......................#',
      '#.....PPPPPPPPPPPPP.....#',
      '#.......................#',
      '#..P....P.GGGGG.P....P..#',
      '#..P....P.GGGGG.P....P..#',
      '#..P....P.GGGGG.P....P..#',
      '#.......................#',
      '#....PPPPP.....PPPPP....#',
      '#.......................#',
      '#..GGG..GGG..GGG..GGG...#',
      '#..GGG..GGG..GGG..GGG...#',
      '#..GGG..GGG..GGG..GGG...#',
      '#..GGG..GGG..GGG..GGG...#',
      '#..GGG..GGG..GGG..GGG...#',
      '#..GGG..GGG..GGG..GGG...#',
      '#..GGG..GGG..GGG..GGG...#',
      '#..GGG..GGG..GGG..GGG...#'
    ]
  },
  {
    id: 6,
    name: '十字回廊',
    rows: [
      '#########################',
      '#GGGGGGGGGGGGGGGGGGGGGGG#',
      '#GGGGGYGGGGGYGGGGGYGGGGG#',
      '#GGGGVGGGGGGGGGGGGGVGGGG#',
      '#.......................#',
      '#.......................#',
      '#GGGGG..BBB###BBB..GGGGG#',
      '#GG.GG..G.G###G.G..GG.GG#',
      '#GR###..#########..###RG#',
      '#GGGGG..GG.GGG.GG..GGGGG#',
      '#GP.GG..GG.GGG.GG..GG.PG#',
      '#GG###..#########..###GG#',
      '#GGGGG..BBB###BBB..GGGGG#',
      '#G.....................G#',
      '#G.....................G#',
      '#GGGGYGGGGGGGGGGGGGYGGGG#',
      '#GGGGGGGGVGGGGGGGVGGGGGG#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#'
    ]
  },
  {
    id: 7,
    name: '阶梯墙阵',
    rows: [
      '#########################',
      '#GGGGGGGGGGGGGGGGGGGGGGG#',
      '#GGGGGGGGGGGGGGGGGGGGGGG#',
      '#G.....................G#',
      '#G.....................G#',
      '#G..BGGGGGYGGGYGGGGGB..G#',
      '#G..G###############G..G#',
      '#G.....GGGGGG#GGGG.....G#',
      '#G..G#GG.........GG#G..G#',
      '#G..G#GG..GG..GG.GG#G..G#',
      '#G..G#GG....BB...GG#G..G#',
      '#G..G#GG....BB...GG#G..G#',
      '#G..G#GG....BB...GG#G..G#',
      '#G..G#GGGGGGGGGGGGG#G..G#',
      '#G..G###############G..G#',
      '#G..VGGGBGGGGGGGBGGGV..G#',
      '#G.....................G#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#'
    ]
  },
  {
    id: 8,
    name: '窄门反射',
    rows: [
      '#########################',
      '#GGGGGGGGGBBBBBGGGGGGGGG#',
      '#GGGGGGGGGG...GGGGGGGGGG#',
      '#GGGGGGGGGG...GGGGGGGGGG#',
      '#GG......#######......GG#',
      '#GG........###........GG#',
      '#BBBGGGGGGB...GGGGGGGGGG#',
      '#P#########...BGGGGGGBBB#',
      '#GGGGGGGGGG...#########P#',
      '#GGGGGGGGGG.#.GGGGGGGGGG#',
      '#GGGGGGGGGG###GGGGGGGGGG#',
      '#GG.........#.........GG#',
      '#GG...................GG#',
      '#GGGGGGGG#V...V#GGGGGGGG#',
      '#GGGG######...######GGGG#',
      '#GG##GGGVGG...GGVGGG##GG#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#'
    ]
  },
  {
    id: 9,
    name: '回字阵',
    rows: [
      '#########################',
      '#GGGGGGGYRGGGGGRYGGGGGGG#',
      '#GGGGGGGYRGGGGGRYGGGGGGG#',
      '#GG...................GG#',
      '#GG...................GG#',
      '#GG.....#########.....GG#',
      '#GG.....#BBBBBBB#.....GG#',
      '#GG.....#B.....B#.....GG#',
      '#GG.....#B..G..B#.....GG#',
      '#GG.....#B.....B#.....GG#',
      '#GG.....#BBBBBBB#.....GG#',
      '#GG.....#########.....GG#',
      '#GG...................GG#',
      '#GG...................GG#',
      '#GGGGGGGGGGGGGGGGGGGGGGG#',
      '#GGGGGGGGGGGGGGGGGGGGGGG#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#'
    ]
  },
  {
    id: 10,
    name: '爱心终局',
    bgm: 'assets/audio/level-10-bgm.mp3',
    rows: [
      '#########################',
      '#......GGGG...GGGG......#',
      '#....BGGGGGG.GGGGGGB....#',
      '#...GGGYYGGRRRGGYYGGG...#',
      '#..GGGYGGYGRRRGYGGYGGG..#',
      '#..GGGGVVGGGGGGGVVGGGG..#',
      '#...GGGVVGGGGGGGVVGGG...#',
      '#....GGGGGGGGGGGGGGG....#',
      '#.....GGGGGGGGGGGGG.....#',
      '#......GGGGBBBGGGG......#',
      '#.......GGGGBGGGG.......#',
      '#........GGGGGGG........#',
      '#.........GGGGG.........#',
      '#..........GGG..........#',
      '#...........G...........#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#',
      '#.......................#'
    ]
  }
];

module.exports = {
  defaultLevels: DEFAULT_LEVELS
};
