'use strict';

var fs = require('fs');
var path = require('path');

var rootDir = path.resolve(__dirname, '..');
var runtimeSource = fs.readFileSync(path.join(rootDir, 'src/minigame-runtime.js'), 'utf8');
var appSource = fs.readFileSync(path.join(rootDir, 'src/minigame-app.js'), 'utf8');
var audioSource = fs.readFileSync(path.join(rootDir, 'src/audio.js'), 'utf8');
var defaultLevelsSource = fs.readFileSync(path.join(rootDir, 'src/default-levels.js'), 'utf8');
var gameMetaSource = fs.readFileSync(path.join(rootDir, 'src/game-meta.js'), 'utf8');
var threeScopeSource = fs.readFileSync(path.join(rootDir, 'src/three-scope.js'), 'utf8');
var readmeSource = fs.readFileSync(path.join(rootDir, 'README.md'), 'utf8');
var projectConfig = JSON.parse(fs.readFileSync(path.join(rootDir, 'project.config.json'), 'utf8'));
var gameConfig = JSON.parse(fs.readFileSync(path.join(rootDir, 'game.json'), 'utf8'));
var bgmPath = path.join(rootDir, 'assets/audio/bgm.mp3');
var bgmSize = fs.existsSync(bgmPath) ? fs.statSync(bgmPath).size : 0;
var level10BgmPath = path.join(rootDir, 'assets/audio/level-10-bgm.mp3');
var level10BgmSize = fs.existsSync(level10BgmPath) ? fs.statSync(level10BgmPath).size : 0;
var failures = [];

function ok(message) {
  console.log('OK  ', message);
}

function assert(condition, message) {
  if (!condition) {
    failures.push(message);
    console.log('FAIL', message);
    return;
  }
  ok(message);
}

function contains(source, text) {
  return source.indexOf(text) !== -1;
}

var threeScope = require('../src/three-scope');
var THREE = threeScope.createScopedThreejs({
  width: 1,
  height: 1,
  getContext: function () {
    return {};
  }
});
require('../src/minigame-runtime');
require('../src/minigame-app');
require('../src/audio');
var defaultLevels = require('../src/default-levels').defaultLevels;

assert(THREE.REVISION === '162', 'Three.js r162 local module loads through scoped adapter');
assert(projectConfig.compileType === 'game', 'project.config.json uses WeChat game compile type');
assert(gameConfig.deviceOrientation === 'portrait', 'game.json keeps portrait orientation');
assert(contains(appSource, 'createScopedThreejs') && contains(threeScopeSource, 'safeInstallProperty') && contains(threeScopeSource, 'createElementNS'), 'App uses WeChat scoped Three.js adapter');
assert(contains(appSource, 'onShareAppMessage') && contains(appSource, 'onShareTimeline') && contains(gameMetaSource, '方块破坏王 自定义地图，设计自己的玩法') && contains(gameMetaSource, "query: 'from=share'") && !contains(gameMetaSource, '得分') && !contains(gameMetaSource, 'level='), 'Share card uses the custom-map summary instead of score or level text');
assert(contains(runtimeSource, 'WebGLRenderer') && contains(runtimeSource, 'OrthographicCamera') && contains(runtimeSource, 'CanvasTexture'), 'Runtime renders gameplay and UI with Three.js');
assert(!contains(runtimeSource, 'shouldShowTopHud') && !contains(runtimeSource, 'drawTopHud') && !contains(runtimeSource, 'drawChip') && contains(runtimeSource, "'#fff159'") && !contains(runtimeSource, 'dangerLine'), 'Title and gameplay screens remove the old top HUD and keep the clearer comic title layout');
assert(!contains(runtimeSource, 'coins') && !contains(readmeSource, '金币'), 'Coin storage, rewards, HUD, and documentation are removed');
assert(contains(runtimeSource, "'自定义关卡'") && contains(runtimeSource, "'挑战默认关卡'") && contains(runtimeSource, "'默认关卡编辑器'") && !contains(runtimeSource, "'编辑默认关卡'") && !contains(runtimeSource, "'开始闯关'"), 'Title screen makes custom levels primary while exposing the default-level editor without challenge-mode wording');
assert(contains(runtimeSource, 'fireSalvo') && contains(runtimeSource, 'aimActive') && contains(runtimeSource, 'getAimDirection') && contains(runtimeSource, 'getAimPrediction') && contains(runtimeSource, 'castAimRay') && contains(runtimeSource, 'reflectDirection'), 'Hold-drag aiming, one-bounce prediction, and release shooting are implemented');
assert(contains(runtimeSource, 'PADDLE_DRAG_BASE_GAIN = 1.32') && contains(runtimeSource, 'PADDLE_DRAG_FAST_GAIN = 1.62') && contains(runtimeSource, 'createPaddleDragState') && contains(runtimeSource, 'screenDeltaToWorld') && contains(runtimeSource, 'getPaddleDragGain') && contains(runtimeSource, 'updatePaddleFromDrag') && !contains(runtimeSource, 'this.updatePaddleFromScreen(point.x);'), 'Paddle touch control uses relative drag with fast-swipe gain and no touch-start snap');
assert(contains(runtimeSource, 'STARTING_LIVES = 3') && contains(runtimeSource, 'this.lives = STARTING_LIVES') && contains(runtimeSource, "'生命 ' + this.lives") && contains(runtimeSource, 'this.finishGame(false)') && contains(runtimeSource, 'this.lives = Math.max(0, this.lives - 1)') && contains(runtimeSource, "this.setMessage('生命剩余 ' + this.lives") && contains(runtimeSource, 'clearPowerupDrops') && contains(runtimeSource, 'this.readyToShoot || this.balls.length || this.pendingBalls.length'), 'Runs use three lives, clear power-up drops when a volley ends, and only settle when lives reach zero');
assert(contains(runtimeSource, 'getLaunchBallCount') && contains(runtimeSource, 'return 1;') && contains(runtimeSource, 'var count = this.getLaunchBallCount()'), 'Default launch always starts with one white ball through the shared launch-count helper');
assert(contains(runtimeSource, 'resetGameProgress') && contains(runtimeSource, 'resetShotState') && contains(runtimeSource, 'PADDLE_BASE_WIDTH') && !contains(runtimeSource, 'this.xp') && !contains(runtimeSource, 'xpNeed') && !contains(runtimeSource, 'cannonLevel') && !contains(runtimeSource, 'autoUpgradeCannon'), 'Runs and next levels reset to the initial one-ball state with no experience or cannon progression');
assert(contains(runtimeSource, 'resolvePaddleCollision') && contains(runtimeSource, 'resolveBrickCollision') && contains(runtimeSource, 'checkVolleyFinished') && !contains(runtimeSource, 'shiftBricksDown') && !contains(runtimeSource, 'addTopRow') && !contains(runtimeSource, 'DANGER_Y'), 'Ball, paddle, brick collision are implemented without falling rows or a danger line');
assert(contains(runtimeSource, 'sweptCircleRect') && contains(runtimeSource, 'BALL_COLLISION_STEP') && contains(runtimeSource, 'bestHit'), 'Swept collision prevents fast balls from tunneling through bricks and wall blocks');
assert(contains(runtimeSource, 'PLAY_TOP') && contains(runtimeSource, 'getWallResponseNormal') && contains(runtimeSource, 'brick.row === 0'), 'Top wall collision uses the gray wall inner face and prevents escape through perimeter walls');
assert(contains(runtimeSource, 'MAX_RENDER_PIXEL_RATIO = 1.5') && contains(runtimeSource, 'MAX_UI_PIXEL_RATIO = 2') && contains(appSource, 'MAX_RENDER_PIXEL_RATIO = 1.5') && contains(appSource, 'devicePixelRatio: devicePixelRatio') && contains(runtimeSource, 'this.uiPixelRatio') && contains(runtimeSource, 'utils.createCanvas(this.width, this.height, this.uiPixelRatio)') && contains(runtimeSource, 'this.uiTexture.generateMipmaps = false') && contains(runtimeSource, 'isPowerOfTwo') && contains(runtimeSource, 'THREE.ClampToEdgeWrapping') && contains(runtimeSource, 'withFilteredThreeWarnings') && contains(runtimeSource, 'EXT_blend_minmax extension not supported') && contains(runtimeSource, 'OES_vertex_array_object extension not supported') && contains(runtimeSource, 'antialias: false') && contains(runtimeSource, 'this.renderer.sortObjects = false') && contains(runtimeSource, 'ACTIVE_FRAME_INTERVAL_MS') && contains(runtimeSource, 'IDLE_FRAME_INTERVAL_MS') && contains(runtimeSource, 'getTargetFrameIntervalMs') && contains(runtimeSource, 'FRAME_SKIP_TOLERANCE_MS') && contains(runtimeSource, 'getUiFrameKey') && contains(runtimeSource, 'this.uiTexture.needsUpdate = true') && contains(runtimeSource, 'frameKey === this.lastUiFrameKey'), 'Runtime caps render resolution, uses a higher-resolution UI texture for crisp text, clamps NPOT textures, filters known benign WeChat extension warnings, throttles render cadence, disables object sorting, and updates the full-screen UI texture only when its frame key changes');
assert(contains(runtimeSource, 'brickGrid') && contains(runtimeSource, 'getBrickCollisionCandidates') && contains(runtimeSource, 'this.bricksDirty') && contains(runtimeSource, 'createSharedGeometries') && contains(runtimeSource, 'createBrickMaterials') && contains(runtimeSource, 'this.geometries.eraseLine') && contains(runtimeSource, 'puffMaterial') && contains(runtimeSource, 'MAX_ACTIVE_EFFECTS') && contains(runtimeSource, 'pruneEffectQueue'), 'Runtime uses brick grid collision candidates, shared geometry/materials, dirty brick syncing, shared erase-effect resources, and capped effects for mobile performance');
assert(contains(runtimeSource, 'createPaperTexture') && contains(runtimeSource, 'createComicInkTexture') && contains(runtimeSource, 'spawnEraseEffect') && contains(runtimeSource, 'syncEraseEffect') && contains(runtimeSource, 'brick.outline'), 'Comic book hand-drawn style uses paper texture, ink hatching, thick outlines, and erasure effects');
assert(contains(runtimeSource, 'BRICK_OUTLINE_INSET') && contains(runtimeSource, 'angle = 0;') && !contains(runtimeSource, 'sketchAngle') && !contains(runtimeSource, 'sketchSeed') && !contains(runtimeSource, 'Math.sin(this.elapsed * 4 + brick'), 'Dense brick grids keep stable square cells while hand-drawn style comes from textures and effects');
assert(contains(runtimeSource, 'GREEN_BRICK_COLORS') && contains(runtimeSource, 'green: 0x4fbd73') && contains(runtimeSource, 'toneIndex') && contains(runtimeSource, 'getBrickMaterial') && contains(runtimeSource, "this.brickMaterials['green:' + i]"), 'Ordinary green bricks use softer shared hand-drawn color variants instead of one bright flat green');
assert(contains(runtimeSource, 'COLS = 25') && contains(runtimeSource, 'BOARD_WIDTH = 4.86') && contains(runtimeSource, 'getBoardMetrics'), 'Brick grid uses dense small cells aligned within the visible screen');
assert(defaultLevels.length === 10 && defaultLevels.every(function (level) {
  return level.rows && level.rows.length === 22 && level.rows.every(function (row) {
    return row.length === 25 && /^[#.GBYVRP]+$/.test(row);
  });
}) && contains(defaultLevelsSource, 'Legend:') && contains(defaultLevelsSource, "name: '分裂教学'") && contains(defaultLevelsSource, "name: '激光教学'") && contains(runtimeSource, "require('./default-levels')") && contains(runtimeSource, 'buildConfiguredLevelCells') && contains(runtimeSource, 'DEFAULT_LEVELS.length || 10') && contains(runtimeSource, 'getDefaultLevelTemplateSignature') && contains(runtimeSource, 'templateSignature'), 'Default level maps are stored as readable 25x22 ASCII config and parsed with source-change cache invalidation');
assert(contains(runtimeSource, 'isIntroCorridorCell') && contains(runtimeSource, 'isIntroWallCell') && contains(runtimeSource, 'isIntroPracticeGap') && contains(runtimeSource, 'isAdvancedCorridorCell') && contains(runtimeSource, 'isAdvancedWallCell') && contains(runtimeSource, 'isAdvancedPracticeGap') && contains(runtimeSource, 'isReferenceCorridorCell') && contains(runtimeSource, 'isReferenceWallCell') && contains(runtimeSource, 'cellInRect') && contains(runtimeSource, 'shouldPlaceWallBrick') && contains(runtimeSource, 'planInitialSkillBricks') && contains(runtimeSource, 'getInitialSkillQuota') && contains(runtimeSource, 'BRICK_POWER_BY_COLOR'), 'Default levels keep fallback generators for intro, reference, tutorial, and advanced stages while configured maps stay sparse with skill and wall bricks');
assert(contains(runtimeSource, 'MAX_ACTIVE_POWERUPS = 5') && contains(runtimeSource, 'MAX_QUEUED_POWERUPS = 32') && contains(runtimeSource, 'releaseQueuedPowerups') && !contains(runtimeSource, 'NORMAL_POWER_DROP_CHANCE') && !contains(runtimeSource, "dropPowerup(brick.x, brick.y, '')") && !contains(runtimeSource, 'TOP_ROW_SKILL_INTERVAL'), 'Only special skill bricks drop power-ups while active drops stay capped and overflow drops queue instead of disappearing');
assert(contains(runtimeSource, 'blue: 0x1479ff') && contains(runtimeSource, 'gold: 0xffb000') && contains(runtimeSource, 'violet: 0x8a2cff') && contains(runtimeSource, 'crimson: 0xff2f2f') && contains(runtimeSource, 'pink: 0xff4fd8') && !contains(runtimeSource, 'cyan: 0x29d6ff'), 'Special brick colors use high-contrast colors distinct from ordinary green');
assert(contains(runtimeSource, "split: '#1479ff'"), 'Split power-up icon uses the same blue identity as blue split bricks');
assert(contains(runtimeSource, "laser: '#ff4fd8'"), 'Laser power-up icon uses the same pink identity as pink laser bricks');
assert(contains(runtimeSource, 'if (brick.wall)') && contains(runtimeSource, 'isBreakableWallBrick') && contains(runtimeSource, 'strong && this.isBreakableWallBrick(brick)') && contains(runtimeSource, 'ball.vx *= -1') && contains(runtimeSource, 'brick.hp = 0') && contains(runtimeSource, 'dropPowerup(brick.x, brick.y, BRICK_POWER_BY_COLOR'), 'Collision semantics keep normal walls reflective, let heavy balls break internal gray walls, and make non-wall bricks removable with power drops');
assert(contains(runtimeSource, "blue: 'split'") && contains(runtimeSource, "gold: 'heavy'") && contains(runtimeSource, "violet: 'shotgun'") && contains(runtimeSource, "crimson: 'bomb'") && contains(runtimeSource, "pink: 'laser'") && contains(runtimeSource, 'this.queuedPowerups.push') && !contains(runtimeSource, 'this.removePowerupAt(0)'), 'Every skill brick color has a matching power-up drop and overflow uses a queue instead of culling visible falling items');
assert(contains(runtimeSource, 'getPowerIconTexture') && contains(runtimeSource, 'drawPowerIconTexture') && contains(runtimeSource, 'drawPowerSplitIcon') && contains(runtimeSource, 'drawPowerHeavyIcon') && contains(runtimeSource, 'drawPowerShotgunIcon') && contains(runtimeSource, 'drawPowerBombIcon') && contains(runtimeSource, 'drawPowerLaserIcon') && contains(runtimeSource, 'this.geometries.power') && !contains(runtimeSource, 'OctahedronGeometry(0.14'), 'Falling power-ups use shared geometry with hand-drawn Canvas icon textures instead of generic geometric gems');
assert(contains(runtimeSource, 'this.geometries.brickPowerIcon') && contains(runtimeSource, 'BRICK_W * 1.5') && contains(runtimeSource, 'getPowerIconMaterial') && contains(runtimeSource, 'brick.powerIcon') && contains(runtimeSource, 'BRICK_POWER_BY_COLOR[brick.colorKey]') && contains(runtimeSource, 'if (powerType)') && contains(runtimeSource, 'brick.mesh = null') && contains(runtimeSource, 'brick.outline = null'), 'Special skill bricks render directly as large hand-drawn power-up sticker art without an extra colored brick wrapper');
assert(contains(runtimeSource, "this.state = 'help'") && contains(runtimeSource, 'drawHelp') && contains(runtimeSource, 'wrapHelpText') && contains(runtimeSource, 'drawHelpSectionTitle') && contains(runtimeSource, 'drawHelpSkill') && contains(runtimeSource, 'drawHelpPowerIcon') && contains(runtimeSource, 'ctx.drawImage(image') && !contains(runtimeSource, 'this.drawPowerLegend(ctx'), 'Power-up descriptions live on an independent wrapped help screen with matching icon art instead of overlapping or overflowing the play field');
assert(contains(runtimeSource, 'UI_BUTTON_HEIGHT = 42') && contains(runtimeSource, 'UI_BUTTON_RADIUS = 12') && contains(runtimeSource, 'drawButton') && contains(runtimeSource, 'Math.round(rect.x)') && contains(runtimeSource, 'fontSize || 16') && contains(runtimeSource, 'createButtonRect') && contains(runtimeSource, 'this.drawButton(ctx, rect') && contains(runtimeSource, 'drawGameplayStatusChip') && contains(runtimeSource, "'重型弹 ' + Math.ceil(this.heavyTimer)") && contains(readmeSource, '统一使用同一套漫画书按钮规格') && contains(readmeSource, '底部信息条边侧小标签'), 'Visible text buttons and gameplay status chips use consistent, crisp, non-overlapping layouts across screens');
assert(contains(runtimeSource, 'drawReadyLaunchGuide') && contains(runtimeSource, 'drawPaddleReadyBall') && contains(runtimeSource, 'drawOpeningGuideSwipeTrack') && contains(runtimeSource, 'drawOpeningGuideDots') && contains(runtimeSource, 'drawOpeningGuideHand') && contains(runtimeSource, 'getOpeningGuideHandImage') && contains(runtimeSource, 'utils.createCanvas(128, 128, 3)') && contains(runtimeSource, 'openingGuideVisible') && contains(runtimeSource, '左右拖动调角度，松开发射'), 'Title and opening play states show a ready ball on the paddle with a horizontal drag-to-aim guide');
assert(!contains(runtimeSource, "this.touchRects.upgrade") && !contains(runtimeSource, "key === 'upgrade'") && !contains(runtimeSource, "this.drawSmallButton(ctx, this.touchRects.help, '说明')") && !contains(runtimeSource, "this.drawCompactButton(ctx, button"), 'Gameplay and title UI remove manual help and cannon upgrade buttons');
assert(contains(runtimeSource, "key === 'endGame'") && contains(runtimeSource, 'endCurrentGame') && contains(runtimeSource, "this.touchRects.endGame") && contains(runtimeSource, "'结束游戏'") && contains(runtimeSource, 'this.audio.stopBgm()') && contains(runtimeSource, 'this.resetTitlePreview()'), 'Gameplay exposes an end-game action that stops music and returns to the title screen');
assert(contains(runtimeSource, 'BALL_STUCK_TIME') && contains(runtimeSource, 'BALL_WALL_LOOP_LIMIT') && contains(runtimeSource, 'updateBallStuckState') && contains(runtimeSource, 'breakBallLoop') && !contains(runtimeSource, 'BALL_MAX_AGE') && !contains(runtimeSource, '回收卡住的弹球'), 'Ball loop watchdog redirects stuck balls without age-based or in-field removal');
assert(contains(runtimeSource, 'clearBrickMeshes') && contains(runtimeSource, 'clearBrickMesh(brick)') && contains(runtimeSource, 'this.clearBrickMesh(brick)'), 'Destroyed and regenerated bricks clear their meshes so removed cells stay empty');
assert(contains(runtimeSource, 'DEFAULT_LEVEL_COUNT = DEFAULT_LEVELS.length || 10') && contains(runtimeSource, 'DEFAULT_LEVEL_TEMPLATE_VERSION = 10') && contains(runtimeSource, 'getBrickHpForLevel') && contains(runtimeSource, 'startNextLevel') && contains(runtimeSource, "'levelclear'") && contains(runtimeSource, "'下一关'") && contains(runtimeSource, 'isLevelTwoCorridorCell') && contains(runtimeSource, 'isLevelTwoWallCell') && contains(runtimeSource, 'shouldLeavePracticeGap') && contains(runtimeSource, 'isLevelTwoPracticeGap') && !contains(runtimeSource, 'ensureDefaultOpenRoutes') && !contains(runtimeSource, 'getUnreachableBreakableCells') && !contains(runtimeSource, 'repairUnreachableBreakables') && contains(readmeSource, '第 1-5 关是低难度道具教学关') && contains(readmeSource, '技能砖数量更密集') && contains(readmeSource, '普通绿砖只保留少量') && contains(readmeSource, '运行时不会再开墙、清砖或转换地图') && contains(readmeSource, '保留当前网格原样'), 'Default mode supports a ten-level campaign with configured maps while removing hidden route repair and rule conversion');
assert(contains(runtimeSource, 'tryCompleteLevel') && contains(runtimeSource, 'COMPLETE_SLOWMO_DURATION') && contains(runtimeSource, 'COMPLETE_SLOWMO_SCALE') && contains(runtimeSource, 'prepareFinalBrickVisual') && contains(runtimeSource, 'syncFinalClearingBrick') && contains(runtimeSource, 'brick.finalClear') && contains(runtimeSource, 'cloneMaterialForFinalClear') && contains(runtimeSource, 'beginLevelCompleteSlowMotion') && contains(runtimeSource, "this.state = 'completing'") && contains(runtimeSource, 'finalizeLevelComplete') && contains(runtimeSource, 'drawCompletionSlowMotion') && contains(runtimeSource, 'clearPlayfieldForResult') && contains(runtimeSource, "'victory'") && contains(runtimeSource, "this.setMessage('关卡完成'"), 'Clearing all removable bricks plays a visible final-brick slow-motion disappearance before level transition or settlement');
assert(contains(runtimeSource, 'clearActiveEntities') && contains(runtimeSource, 'clearGroup(this.ballGroup)') && contains(runtimeSource, 'clearGroup(this.powerGroup)') && contains(runtimeSource, 'clearGroup(this.effectGroup)') && contains(runtimeSource, 'if (!power)') && contains(runtimeSource, 'this.collectPower(power.type);') && contains(runtimeSource, "if (this.state !== 'playing')"), 'Result transitions clear transient Three.js meshes and power-up loops stop after final-brick completion');
assert(contains(runtimeSource, 'ACTIVE_FRAME_INTERVAL_MS = 1000 / 60') && contains(runtimeSource, 'new THREE.CircleGeometry(BALL_RADIUS, 28)') && contains(runtimeSource, 'BALL_OUTLINE_RATIO = 1.15') && contains(runtimeSource, 'ink.position.z = BALL_OUTLINE_Z') && contains(runtimeSource, 'body.position.z = BALL_BODY_Z') && contains(runtimeSource, 'BALL_RENDER_Z'), 'Ball rendering uses a flat crisp body with a close outline and 60fps active motion to avoid moving ghost artifacts');
assert(contains(runtimeSource, 'runStats') && contains(runtimeSource, 'drawSettlementItem') && contains(runtimeSource, "'本局结算'") && contains(runtimeSource, "'本局用时'") && contains(runtimeSource, 'formatRunDuration') && contains(runtimeSource, 'getRunDurationSeconds') && contains(runtimeSource, 'freezeRunTimer') && contains(runtimeSource, "'击碎方块'") && contains(runtimeSource, "'收集道具'") && contains(runtimeSource, "'发射次数'") && !contains(runtimeSource, 'this.score') && !contains(runtimeSource, 'bestScore') && !contains(runtimeSource, "'本局得分'") && !contains(runtimeSource, "'获得经验'") && !contains(runtimeSource, "ctx.fillText('结果："), 'Result screen records whole-second duration, shots, bricks, and power-ups without score or experience text');
assert(contains(runtimeSource, 'MAX_BALLS = 48') && contains(runtimeSource, 'POWER_TYPES') && contains(runtimeSource, 'splitBalls') && contains(runtimeSource, 'triggerBomb') && contains(runtimeSource, 'triggerLaser') && contains(runtimeSource, 'fireShotgun') && contains(runtimeSource, 'isPowerupCaught') && contains(runtimeSource, 'applyHeavyToActiveBalls') && contains(runtimeSource, 'updateHeavyBallState') && contains(runtimeSource, 'heavyActive ? Math.max') && contains(runtimeSource, 'suppressPowerDrop'), 'Power-up system includes split with a higher 48-ball cap, timed heavy, shotgun, bomb, laser, forgiving pickup, and non-chaining skill clears');
assert(!contains(runtimeSource, 'upgradeCannon') && !contains(runtimeSource, 'autoUpgradeCannon') && !contains(runtimeSource, 'addXp') && !contains(runtimeSource, 'xpNeed'), 'Experience and automatic cannon growth are removed from gameplay');
assert(contains(runtimeSource, 'enterEditor') && contains(runtimeSource, 'enterDefaultEditor') && contains(runtimeSource, 'saveCustomLevel') && contains(runtimeSource, 'saveDefaultLevel') && contains(runtimeSource, 'exportDefaultLevelConfig') && contains(runtimeSource, 'buildDefaultLevelConfigSnippet') && contains(runtimeSource, 'writeExportedDefaultLevelConfig') && contains(runtimeSource, 'STORAGE_EXPORTED_DEFAULT_LEVEL') && !contains(runtimeSource, 'setClipboardData') && contains(runtimeSource, 'playCustomLevel') && contains(runtimeSource, 'editorGrid') && contains(runtimeSource, "['green', 'blue', 'gold', 'violet', 'crimson', 'pink', 'wall', 'erase']") && contains(runtimeSource, 'powerType = BRICK_POWER_BY_COLOR[tool]') && contains(runtimeSource, 'this.drawHelpPowerIcon(ctx, powerType'), 'Custom and default level editors with local saves and config export are implemented without clipboard privacy permissions');
assert(contains(runtimeSource, 'var panelH = 196') && contains(runtimeSource, "this.drawMainButton(ctx, this.touchRects.title, '返回游戏'") && contains(runtimeSource, "this.drawMainButton(ctx, this.touchRects.clearLevel, '清空'") && contains(runtimeSource, "this.drawMainButton(ctx, this.touchRects.saveLevel, '保存'") && contains(runtimeSource, "this.drawMainButton(ctx, this.touchRects.playCustom, '挑战'") && contains(runtimeSource, "'保存默认'") && contains(runtimeSource, "'导出配置'") && contains(runtimeSource, "'试玩默认'") && !contains(runtimeSource, "'" + String.fromCharCode(20943, 30742) + "'") && !contains(runtimeSource, "'" + String.fromCharCode(24320, 36335) + "'") && !contains(runtimeSource, "this.touchRects.title = { x: 16, y: this.getSafeTop() + 18") && contains(readmeSource, '底部控制台'), 'Level editor keeps every action button at the bottom using the same comic button style without extra shortcut optimization buttons');
assert(bgmSize > 0 && bgmSize < 1024 * 1024, 'Compressed background music is bundled under 1 MB');
assert(level10BgmSize > 0 && level10BgmSize < 1024 * 1024 && defaultLevels[9].bgm === 'assets/audio/level-10-bgm.mp3', 'Level 10 has a bundled under-1 MB dedicated background music track');
assert(contains(audioSource, 'BGM_SRC') && contains(audioSource, 'assets/audio/bgm.mp3') && contains(audioSource, 'createInnerAudioContext') && contains(audioSource, 'setBgmSource') && contains(audioSource, 'playBgm = function (src)') && contains(audioSource, 'stopBgm') && contains(audioSource, 'loop = true') && contains(audioSource, 'AudioManager.prototype.resume = function () {\n  var ctx = this.ensure();\n  if (ctx && ctx.resume)'), 'Background music uses compressed local MP3 tracks through InnerAudioContext, supports per-level switching, and is not restarted by generic audio resume');
assert(contains(audioSource, 'createOscillator') && contains(audioSource, 'createBufferSource') && contains(audioSource, 'playShoot') && contains(audioSource, 'playBomb') && contains(audioSource, 'playAimStart') && contains(audioSource, 'playPaddleCatch') && contains(audioSource, 'playBrickBreak') && contains(audioSource, 'playPowerDrop') && contains(audioSource, 'playClear') && contains(runtimeSource, 'playEditorPlace'), 'Audio is synthesized with Web Audio API and covers aiming, catches, breaks, drops, editor actions, and completion');
assert(contains(readmeSource, '默认只有 1 颗白色弹球') && contains(readmeSource, '首次碰撞点') && contains(readmeSource, '只有掉出底部') && contains(readmeSource, '3` 条命') && contains(readmeSource, '生命归零') && contains(readmeSource, '十关制') && contains(readmeSource, '第 1-5 关') && contains(readmeSource, '第 6-10 关') && contains(readmeSource, '下一关') && contains(readmeSource, '自定义关卡作为核心玩法') && !contains(readmeSource, '开始闯关'), 'README documents the one-ball default, three-life rule, aim prediction, persistent balls, and ten-level default campaign flow');
assert(contains(readmeSource, '结算面板') && contains(readmeSource, '本局用时') && contains(readmeSource, '精确到秒') && contains(readmeSource, '击碎方块') && contains(readmeSource, '发射次数') && contains(readmeSource, '避免重复显示结果状态'), 'README documents time-based settlement details');
assert(contains(readmeSource, '每个关卡开始时都回到初始发射状态') && contains(readmeSource, '固定 `1` 颗白色弹球') && contains(readmeSource, '不保存跨局成长数据') && !contains(readmeSource, '经验') && !contains(readmeSource, '炮台'), 'README documents fixed one-ball starts with no experience or cannon growth');
assert(contains(readmeSource, '战斗界面底部不再显示额外说明按钮') && !contains(readmeSource, '砖块会从上方向下推进'), 'README documents the optimized gameplay bottom layout and fixed-board rules');
assert(contains(readmeSource, '漫画书手绘风') && contains(readmeSource, '纸张纹理') && contains(readmeSource, '擦除粉尘'), 'README documents the comic hand-drawn visual style');
assert(contains(readmeSource, '粉色激光') && contains(readmeSource, '稳定掉落对应道具') && contains(readmeSource, 'Canvas 程序手绘') && contains(readmeSource, '漫画贴纸图标'), 'README documents guaranteed special-brick drops and hand-drawn falling power-up art');
assert(contains(readmeSource, '不会继续生成二次道具') && contains(readmeSource, '立即强化场上已有弹球'), 'README documents fixed power-up chaining and visible heavy-ball behavior');
assert(contains(readmeSource, '复杂技能') && contains(readmeSource, '说明文字会自动换行') && contains(readmeSource, '失败条件') && !contains(readmeSource, '自动升级'), 'README documents the improved non-overflowing help layout and fuller gameplay explanations');
assert(contains(readmeSource, '背景音乐') && contains(readmeSource, '开始一局时启动') && contains(readmeSource, '进入结算时停止') && !contains(readmeSource, '/Users/') && !contains(readmeSource, '496 KB'), 'README documents background music behavior without copied file details');
assert(contains(readmeSource, '核心玩法') && contains(readmeSource, '美术设计') && contains(readmeSource, '技术设计') && contains(readmeSource, '音频设计') && contains(readmeSource, '自定义关卡'), 'README documents the main gameplay features and design plan');

if (failures.length) {
  console.log('');
  console.log('Smoke validation failed with ' + failures.length + ' issue(s).');
  process.exit(1);
}

console.log('');
console.log('Smoke validation passed.');
